

def init():
    return [{"name": "URU", "elo": 1891, "group": "A", "points": 0, "GF": 0, "GA": 0, "first": 0, "second": 0, "qf": 0, "sf": 0, "champion": 0},
    {"name": "RUS", "elo": 1678, "group": "A", "points": 0, "GF": 0, "GA": 0, "first": 0, "second": 0, "qf": 0, "sf": 0, "champion": 0},
    {"name": "EGY", "elo": 1646, "group": "A", "points": 0, "GF": 0, "GA": 0, "first": 0, "second": 0, "qf": 0, "sf": 0, "champion": 0},
    {"name": "KSA", "elo": 1592, "group": "A", "points": 0, "GF": 0, "GA": 0, "first": 0, "second": 0, "qf": 0, "sf": 0, "champion": 0},
    {"name": "ESP", "elo": 2042, "group": "B", "points": 0, "GF": 0, "GA": 0, "first": 0, "second": 0, "qf": 0, "sf": 0, "champion": 0},
    {"name": "POR", "elo": 1969, "group": "B", "points": 0, "GF": 0, "GA": 0, "first": 0, "second": 0, "qf": 0, "sf": 0, "champion": 0},
    {"name": "IRN", "elo": 1787, "group": "B", "points": 0, "GF": 0, "GA": 0, "first": 0, "second": 0, "qf": 0, "sf": 0, "champion": 0},
    {"name": "MAR", "elo": 1723, "group": "B", "points": 0, "GF": 0, "GA": 0, "first": 0, "second": 0, "qf": 0, "sf": 0, "champion": 0},
    {"name": "FRA", "elo": 1995, "group": "C", "points": 0, "GF": 0, "GA": 0, "first": 0, "second": 0, "qf": 0, "sf": 0, "champion": 0},
    {"name": "PER", "elo": 1916, "group": "C", "points": 0, "GF": 0, "GA": 0, "first": 0, "second": 0, "qf": 0, "sf": 0, "champion": 0},
    {"name": "DEN", "elo": 1843, "group": "C", "points": 0, "GF": 0, "GA": 0, "first": 0, "second": 0, "qf": 0, "sf": 0, "champion": 0},
    {"name": "AUS", "elo": 1733, "group": "C", "points": 0, "GF": 0, "GA": 0, "first": 0, "second": 0, "qf": 0, "sf": 0, "champion": 0},
    {"name": "ARG", "elo": 1986, "group": "D", "points": 0, "GF": 0, "GA": 0, "first": 0, "second": 0, "qf": 0, "sf": 0, "champion": 0},
    {"name": "HSV", "elo": 1848, "group": "D", "points": 0, "GF": 0, "GA": 0, "first": 0, "second": 0, "qf": 0, "sf": 0, "champion": 0},
    {"name": "ISL", "elo": 1770, "group": "D", "points": 0, "GF": 0, "GA": 0, "first": 0, "second": 0, "qf": 0, "sf": 0, "champion": 0},
    {"name": "NGA", "elo": 1681, "group": "D", "points": 0, "GF": 0, "GA": 0, "first": 0, "second": 0, "qf": 0, "sf": 0, "champion": 0},
    {"name": "BRA", "elo": 2136, "group": "E", "points": 0, "GF": 0, "GA": 0, "first": 0, "second": 0, "qf": 0, "sf": 0, "champion": 0},
    {"name": "SUI", "elo": 1886, "group": "E", "points": 0, "GF": 0, "GA": 0, "first": 0, "second": 0, "qf": 0, "sf": 0, "champion": 0},
    {"name": "SER", "elo": 1763, "group": "E", "points": 0, "GF": 0, "GA": 0, "first": 0, "second": 0, "qf": 0, "sf": 0, "champion": 0},
    {"name": "CRC", "elo": 1755, "group": "E", "points": 0, "GF": 0, "GA": 0, "first": 0, "second": 0, "qf": 0, "sf": 0, "champion": 0},
    {"name": "GER", "elo": 2076, "group": "F", "points": 0, "GF": 0, "GA": 0, "first": 0, "second": 0, "qf": 0, "sf": 0, "champion": 0},
    {"name": "MEX", "elo": 1861, "group": "F", "points": 0, "GF": 0, "GA": 0, "first": 0, "second": 0, "qf": 0, "sf": 0, "champion": 0},
    {"name": "SWE", "elo": 1794, "group": "F", "points": 0, "GF": 0, "GA": 0, "first": 0, "second": 0, "qf": 0, "sf": 0, "champion": 0},
    {"name": "KOR", "elo": 1731, "group": "F", "points": 0, "GF": 0, "GA": 0, "first": 0, "second": 0, "qf": 0, "sf": 0, "champion": 0},
    {"name": "ENG", "elo": 1943, "group": "G", "points": 0, "GF": 0, "GA": 0, "first": 0, "second": 0, "qf": 0, "sf": 0, "champion": 0},
    {"name": "BEL", "elo": 1933, "group": "G", "points": 0, "GF": 0, "GA": 0, "first": 0, "second": 0, "qf": 0, "sf": 0, "champion": 0},
    {"name": "PAN", "elo": 1659, "group": "G", "points": 0, "GF": 0, "GA": 0, "first": 0, "second": 0, "qf": 0, "sf": 0, "champion": 0},
    {"name": "TUN", "elo": 1659, "group": "G", "points": 0, "GF": 0, "GA": 0, "first": 0, "second": 0, "qf": 0, "sf": 0, "champion": 0},
    {"name": "COL", "elo": 1928, "group": "H", "points": 0, "GF": 0, "GA": 0, "first": 0, "second": 0, "qf": 0, "sf": 0, "champion": 0},
    {"name": "POL", "elo": 1831, "group": "H", "points": 0, "GF": 0, "GA": 0, "first": 0, "second": 0, "qf": 0, "sf": 0, "champion": 0},
    {"name": "SEN", "elo": 1740, "group": "H", "points": 0, "GF": 0, "GA": 0, "first": 0, "second": 0, "qf": 0, "sf": 0, "champion": 0},
    {"name": "JPN", "elo": 1670, "group": "H", "points": 0, "GF": 0, "GA": 0, "first": 0, "second": 0, "qf": 0, "sf": 0, "champion": 0}
    ]